# - Try to find IRRKLANG
# Once done, this will define
#
# IRRKLANG_FOUND - system has IRRKLANG
# IRRKLANG_INCLUDE_DIR - the IRRKLANG include directories
# IRRKLANG_LIBRARIES - link these to use IRRKLANG
FIND_PATH( IRRKLANG_INCLUDE_DIR irrklang
	/usr/include
	/usr/local/include
	/opt/local/include
	${CMAKE_SOURCE_DIR}/includes
)
FIND_LIBRARY( IRRKLANG_LIBRARY libIrrKlang.so irrKlang
	/usr/lib64
	/usr/lib
	/usr/local/lib
	/opt/local/lib
	${CMAKE_SOURCE_DIR}/lib
)
IF(IRRKLANG_INCLUDE_DIR AND IRRKLANG_LIBRARY)
	SET( IRRKLANG_FOUND TRUE )
	SET( IRRKLANG_LIBRARIES ${IRRKLANG_LIBRARY} )
ENDIF(IRRKLANG_INCLUDE_DIR AND IRRKLANG_LIBRARY)
IF(IRRKLANG_FOUND)
	IF(NOT IRRKLANG_FIND_QUIETLY)
	MESSAGE(STATUS "Found IRRKLANG: ${IRRKLANG_LIBRARY}")
	ENDIF(NOT IRRKLANG_FIND_QUIETLY)
ELSE(IRRKLANG_FOUND)
	IF(IRRKLANG_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find libIRRKLANG")
	ENDIF(IRRKLANG_FIND_REQUIRED)
ENDIF(IRRKLANG_FOUND)
